apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
      - name: survey-app
        image: chaochen46/survey-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: survey-service
spec:
  type: NodePort
  selector:
    app: survey-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080   # http://your NodeIP:30080
